---

- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        Nicolas Cage is the
        Tiger King
      state: present

  - name: Add loopback

    ios_interface:
      name: Loopback21
      state: present 
